### PR TITLE
Discover jobs/hooks in find images and diff git repo patches

### LINKED ISSUE #1246: FindImages doesn't run any images found in Job Hooks
### Environment
Device and OS: Ubuntu 22.04
App version:  0.23.5
Kubernetes distro being used: KRE2

### Steps to reproduce
1.  Provide a helm chart to zarf.yaml (Like Flux) that contains a Job in the hook

kind: ZarfPackageConfig
metadata:
  name: test-helm-local-chart
  description: "Deploys Flux"
components:
  - name: flux
    required: true
    charts:
      - name: flux2
        localPath: charts/flux2
        namespace: flux-system
        version: 2.4.1

Because the Job is a hook, it is not included in the output Template from the Helm chart and as such is not included in the output image list.

### Expected result

Should include the image that the hook job uses that way when deployed air-gapped the container exists in that environment.

### Actual Result
Image is misssing.

### Visual Proof (screenshots, videos, text, etc)

Output of the above helm chart is:

- name: flux
    images:
      - ghcr.io/fluxcd/helm-controller:v0.27.0
      - ghcr.io/fluxcd/image-automation-controller:v0.27.0
      - ghcr.io/fluxcd/image-reflector-controller:v0.23.0
      - ghcr.io/fluxcd/kustomize-controller:v0.31.0
      - ghcr.io/fluxcd/source-controller:v0.32.1

### Additional Context

I think the issue is in chart.go in TemplateChart(), the templatedChart has a hook attribute but that is not included in the Manifest object.  Need to just append the Hook YAML to the existing manifests I believe and the rest of the code should work as it already does.

### PR DESCRIPTION
**Pull request by Racer159**
## Description

Implements hook discovery for images and shows changes from patch-git.

## Related Issue

Fixes #1246 
Relates to #1625 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/message/message.go [hunk 1]
```diff
@@ -243,6 +244,17 @@ func Paragraphn(n int, format string, a ...any) string {
 	return pterm.DefaultParagraph.WithMaxWidth(n).Sprintf(format, a...)
 }
 
+// PrintDiff prints the differences between a and b with a as original and b as new
+func PrintDiff(textA, textB string) {
```
Comment (Noxsios) [inline src/pkg/message/message.go:248]: Does `diffmatchpatch` colorize the output like Git diff does?

Screenshot 2023-04-25 at 5 54 46 PM

**Review by Noxsios — APPROVED** [review]
lgtm, only thing I would change is colorizing the diff output, but thats a trivial change in the future.

File: src/pkg/packager/prepare.go [hunk 2]
```diff
@@ -204,36 +205,38 @@ func (p *Packager) FindImages(baseDir, repoHelmChartPath string) error {
...
+			if len(validImages) > 0 {
+				componentDefinition += fmt.Sprintf("      # Possible images - %s - %s\n", p.cfg.Pkg.Metadata.Name, component.Name)
+				for _, image := range validImages {
+					componentDefinition += fmt.Sprintf("      - %s\n", image)
 				}
 			}
 		}
 	}
 
+	fmt.Println(componentDefinition)
```
Comment (Noxsios) [inline src/pkg/packager/prepare.go:238]: Do we want to create a `message.Text` so that any STDERR/STDOUT redirections from pterm are used globally?

File: src/pkg/message/message.go (hunk 1 above)
Comment (Racer159) [reply src/pkg/message/message.go:248]: It is not quite the same but yes it does - it does it based on character not line:
image

File: src/pkg/packager/prepare.go (hunk 2 above)
Comment (Racer159) [reply src/pkg/packager/prepare.go:238]: I think it is easy enough to use fmt.Println to print things to stdOut - I like that it is very explicit when we are printing to std out vs std err.  One thing I suppose though is that it doesn't currently print that output in the logs - though we only use this in more prepare or tools like scenarios.
