### PR TITLE
fix: remove unpinned image warning in lint for cosign signatures

### LINKED ISSUE #2577: Zarf dev lint warns that cosign signatures are not pinned with a digest
Currently running `zarf dev lint` against a `zarf.yaml` with a cosign signature will give a warning like below. It's redundant as cosign signatures are unique to an image sha, and you will not have two cosign signatures at the same image
```
Image not pinned with digest - ghcr.io/stefanprodan/podinfo:sha256-57a654ace69ec02ba8973093b6a786faa15640575fbf0dbb603db55aca2ccec8.sig
```

If an image has ".sig" at the end, it should simply be ignored from lint

### PR DESCRIPTION
**Pull request by jasonwashburn**
## Description
Removes unpinned image warning generated by `zarf dev lint` for cosign signatures.
...

## Related Issue

Fixes #2577 

## Checklist before merging

- [ x ] Test, docs, adr added or updated as needed
- [ x ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by jasonwashburn** [comment]
@AustinAbro321 Would the preference for this to treat signatures effectively as pinned (`isPinnedImage`)  or rather to add separate handling i.e. `isSignedImage` ?

**Comment by AustinAbro321** [comment]
Thanks @jasonwashburn, looks mostly good. Could you also have the linter ignore ".att" images ending in .att, as these images are also already sha'd and used by cosign for provenance and integrity.

**Comment by jasonwashburn** [comment]
> Thanks @jasonwashburn, looks mostly good. Could you also have the linter ignore ".att" images ending in .att, as these images are also already sha'd and used by cosign for provenance and integrity.

Sure thing!

File: src/pkg/packager/lint/lint.go [hunk 1]
```diff
@@ -144,9 +143,20 @@ func isPinnedImage(image string) (bool, error) {
...
 		return false, err
 	}
+	if isCosignSignature(transformedImage.Tag) || isCosignAttestation(transformedImage.Tag) {
+		return true, nil
+	}
 	return (transformedImage.Digest != ""), err
 }
 
+func isCosignSignature(image string) bool {
+	return (strings.HasSuffix(image, ".sig"))
```
Comment (phillebaba) [inline src/pkg/packager/lint/lint.go:153]: Remove the excessive parentheses wrapping the function.

File: src/pkg/packager/lint/lint.go [hunk 2]
```diff
@@ -144,9 +143,20 @@ func isPinnedImage(image string) (bool, error) {
...
+}
+
+func isCosignAttestation(image string) bool {
+	return (strings.HasSuffix(image, ".att"))
```
Comment (phillebaba) [inline src/pkg/packager/lint/lint.go:157]: Remove the excessive parentheses wrapping the function.

**Review by phillebaba — CHANGES_REQUESTED** [review]
Small NIT otherwise looks good, thank you for expanding the tests to cover this.

File: src/pkg/packager/lint/lint.go (hunk 1 above)
Comment (jasonwashburn) [reply src/pkg/packager/lint/lint.go]: 🤦‍♂️ good catch, fixed!

**Review by phillebaba — APPROVED** [review]
