### PR TITLE
fix: pathing issues loading images with Zarf on Windows

### LINKED ISSUE #2102: Zarf 0.30.1 on Windows 10 does not work anymore
### Environment
Device and OS: Windows 10 Pro
App version: Zarf 0.30.1
Kubernetes distro being used: k3s with zarf included
Other:

### Steps to reproduce
1. Build zarf package with zarf 0.30.1 on linux
2. Deploy same zarf package with zarf 0.30.1 on windows

### Expected result
- Deploying docker images to zarf registry is working

### Actual Result
on 'PushToRegistry' zarf crashes (stack trace).

### Severity/Priority
- Medium/High - since version 0.30.x zarf is not working anymore on Windows platforms

### Additional Context
Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This fixes path issues when Zarf tries to load images on Windows.

## Related Issue

Fixes #2102 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/utils/network_test.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func (suite *TestNetworkSuite) SetupSuite() {
 
 func (suite *TestNetworkSuite) Test_0_parseChecksum() {
 	// zarf prepare sha256sum .adr-dir
-	adr := "https://raw.githubusercontent.com/defenseunicorns/zarf/main/.adr-dir"
+	adr := "https://raw.githubusercontent.com/defenseunicorns/zarf/main/-dir"
```
Comment (Noxsios) [inline src/pkg/utils/network_test.go:28]: Getting a 404 on this removal of `.adr` from this url

File: src/test/common.go [hunk 2]
```diff
@@ -135,3 +136,26 @@ func (e2e *ZarfE2ETest) StripANSICodes(input string) string {
 	ansiRegex := regexp.MustCompile(`\x1b\[(.*?)m`)
 	return ansiRegex.ReplaceAllString(input, "")
 }
+
+func (e2e *ZarfE2ETest) NormalizeYAMLFilenames(input string) string {
```
Comment (Noxsios) [inline src/test/common.go:140]: lint

**Review by Noxsios — CHANGES_REQUESTED** [review]

**Review by Noxsios — APPROVED** [review]
