### PR TITLE
Fix issues with Windows dataInjections

### LINKED ISSUE #1513: Data Injection - Windows Support
### Describe what should be investigated or refactored
The data injection feature currently is not compatible when zarf is started from a Windows Client. In theory, the commands used should be windows compatible e.g. kubectl exec, tar, ...

The main reason it does not work however is that the responsible code block for "Data Injection" requires a shell to be present, it uses "sh -c" in order to start the kubectl commands. As windows does not have a shell by default, it fails.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/blob/main/src/internal/cluster/data.go#L81

### Additional context
It would help to have table to see any known cross platform issues / not implemented features.

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This selects the correct shell on Windows for dataInjections.

## Related Issue

Fixes #1513 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/cluster/data.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func (c *Cluster) HandleDataInjection(wg *sync.WaitGroup, data types.ZarfDataInj
 
 	tarCompressFlag := ""
 	if data.Compress {
-		tarCompressFlag = "z"
+		tarCompressFlag = " -z"
```
Comment (YrrepNoj) [inline src/internal/cluster/data.go:37]: Putting a space at the beginning of this flags feels a bit weird to me 🤷‍♂️

File: src/internal/cluster/data.go [hunk 2]
```diff
@@ -64,48 +72,50 @@ iterator:
...
 			}
 
-			kubectlExec := fmt.Sprintf("%skubectl exec -i -n %s %s -c %s ", binPath, data.Target.Namespace, pod, data.Target.Container)
-			tarExec := fmt.Sprintf("tar c%s", tarCompressFlag)
-			untarExec := fmt.Sprintf("tar x%svf - -C %s", tarCompressFlag, data.Target.Path)
+			kubectlCmd := fmt.Sprintf("%s exec -i -n %s %s -c %s ", kubectlBinPath, data.Target.Namespace, pod, data.Target.Container)
+
+			// Note that each command flag is separated to provide the widest cross-platform tar support
+			tarCmd := fmt.Sprintf("tar -c%s -f -", tarCompressFlag)
+			untarCmd := fmt.Sprintf("tar -x%s -v -f - -C %s", tarCompressFlag, data.Target.Path)
```
Comment (YrrepNoj) [inline src/internal/cluster/data.go:87]: I know this works because we have a space in the flag (that gets set above earlier in the function), but since we have the power to string format this, I prefer something like `-c %s`  over `-c%s` since that more clearly shows that it's two different flags instead of trying to customize what the name of a single flag is.

**Review by YrrepNoj — APPROVED** [review]
I had a small nit, but it's more of a personal preference thing and not something I would prevent from merging in.

File: src/internal/cluster/data.go (hunk 2 above)
Comment (Racer159) [inline src/internal/cluster/data.go:87]:
```suggestion
			tarCmd := fmt.Sprintf("tar -c %s -f -", tarCompressFlag)
			untarCmd := fmt.Sprintf("tar -x %s -v -f - -C %s", tarCompressFlag, data.Target.Path)
```

File: src/internal/cluster/data.go (hunk 1 above)
Comment (Racer159) [inline src/internal/cluster/data.go:37]:
```suggestion
		tarCompressFlag = "-z"
```

**Review by YrrepNoj — APPROVED** [review]
