### PR TITLE
Fix linting and UI version check

### LINKED ISSUE #1614: zarf tools kubectl version returns error code
### Environment
Device and OS: OSX
App version: v0.25.2
Kubernetes distro being used: v1.23.16
Other:

When creating a pre-flight check for the kubernetes version, the zarf tools kubectl command was returning an error. It looks like the clientVersion is not getting set in a way the command likes, potentially based on how its being imported and used by Zarf tools.

### Steps to reproduce
Run the following:

```shell
$ zarf tools kubectl version --short        
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v0.0.0-master+$Format:%H$
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
$ echo $?
1
```

### Expected result
For the return code for the command `zarf tools kubectl version --short ` to be zero.
### Severity/Priority

Simple work around by:

```yaml
  - name: one
    required: true
    actions:
      onDeploy:
        after:
        - cmd: "./zarf tools kubectl version --short || true"
          setVariable: OUTPUT
```

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This cleans up the UI diff check script for local dev and a few linting issues.

## Related Issue

Fixes #1614 
 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/internal/packager/images/pull.go [hunk 1]
```diff
@@ -63,7 +64,7 @@ func (i *ImgConfig) PullAll() error {
 
 	// Create the ImagePath directory
 	err := os.Mkdir(i.ImagesPath, 0755)
-	if err != nil {
+	if err != nil && !errors.Is(err, os.ErrExist) {
```
Comment (YrrepNoj) [inline src/internal/packager/images/pull.go:67]: This might be worth a warning, or double checking our workflow to make sure we are explicit on when we expect this directory to be created.

If this directory already exists when we are running `zarf package create` then there could be unintended contents in that directory that get added to the package (and the checksums since it was there during creation)

Comment (YrrepNoj) [reply src/internal/packager/images/pull.go:67]: Super unlikely, but probably worth consideration

Comment (Racer159) [reply src/internal/packager/images/pull.go:67]: Hmm... You would have to inject something into that directory after zarf create since the tmp dir everything is built from does not exist until that is ran.  If there was malware on the system that wanted to watch your commands all they would have to do now is move that watch to when the image directory is created... (and you would probably want to do this anyway since it would be better to manipulate images that are being run in the cluster rather than just having another image there (and any manifests or layers would get overwritten on crane pull).

This was specifically to fix the retry logic that will try to remake the dir and balk
