### PR TITLE
Fix Importing OCI Components w/ no local resources

### LINKED ISSUE #1772: Zarf Skeleton doesn't like components without local files
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

### Steps to reproduce
1. Create zarf.yaml with these two components:
```yaml
components
- name: init
  required: true
  files:
    - source: zarf-init-amd64-v0.27.0.tar.zst
      target: zarf-init-amd64-v0.27.0.tar.zst
  actions:
    onDeploy:
      after: 
        - cmd: zarf package deploy zarf-init-amd64-v0.27.0.tar.zst --components git-server --confirm -l warn

# This doesnt work with skeletons...
- name: init2
  required: true
  files:
    - source: https://github.com/defenseunicorns/zarf/releases/download/###ZARF_PKG_TMPL_ZARF_VERSION###/zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst
      target: zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst
  actions:
    onDeploy:
      after: 
        - cmd: zarf package deploy zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst --components git-server --confirm -l warn

```

and then publish:

```shell
...
 •  Publishing package to ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
  ✔  Prepared 5 layers                                                                                                                 
  ✔  f1300d0e063c [application/vnd.unknown.config.v1+json]                                                                             
  ✔  48bd8337026e checksums.txt                                                                                                        
  ✔  6e062498132a components/k3d.tar                                                                                                   
  ✔  a256ce800e85 components/metallb.tar                                                                                               
  ✔  7cbacd56c651 zarf.yaml                                                                                                            
  ✔  64e397cf3c44 components/init.tar                                                                                                  
  ✔  236014225522 [application/vnd.oci.image.manifest.v1+json]                                                                         
  ✔  Published ghcr.io/runyontr/k3d-local:v1.26.0-skeleton [application/vnd.oci.image.manifest.v1+json]                                

  •  Example of importing components from this package:

...
```
and note the init2.tar never gets created and pushed.  

Then using that component in a zarf.yaml:

```yaml
  - name: import-init
    required: true
    import:
      name: init2
      url: oci://ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
```


```shell
zarf package create .
...
  •  Pulling Zarf package from ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
  ✔  7cbacd56c651 zarf.yaml                                                                                                                                                                                                                                                                    
  ✔  48bd8337026e checksums.txt                                                                                                                                                                                                                                                                
  ✔  236014225522 [application/vnd.oci.image.manifest.v1+json]                                                                                                                                                                                                                                 
  ✔  Pulling Zarf package data (556.26 MBs)                                                                                                                                                                                                                                                    
  ✔  Pulled ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
     ERROR:  Failed to create package: unable to compose component import-init: unable to get child component:
             unable to unpack composed component tarball: opening source archive: open
             /home/tom/.zarf-cache/oci/ghcr.io/runyontr/k3d-local:v1.26.0-skeleton/components/init2.tar: no such
             file or directory
```


### Expected result

### Actual Result

### Visual Proof (screenshots, videos, text, etc)

### Severity/Priority

### Additional Context
Since there's no local file to put into a tar, I think it's reasonable for nothing to get pushed up, but then the package create shouldn't need to expect it.

### PR DESCRIPTION
**Pull request by Noxsios**
## Description

Fix importing components that do not have any local resources via OCI.

## Related Issue

Fixes #1772 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/packager/compose.go [hunk 1]
```diff
@@ -146,16 +146,25 @@ func (p *Packager) getChildComponent(parent types.ZarfComponent, pathAncestry st
...
+				}
+			}
+			err = archiver.Unarchive(componentTarball, filepath.Join(cachePath, "components"))
 			if err != nil {
-				return child, fmt.Errorf("unable to remove composed component cache path %s: %w", cachePath, err)
+				return child, fmt.Errorf("unable to unpack composed component tarball: %w", err)
+			}
+		} else {
+			// If the tarball doesn't exist (skeleton component had no local resources), we need to create the directory anyways in case there are actions
+			err := utils.CreateDirectory(dir, 0600)
```
Comment (Racer159) [inline src/pkg/packager/compose.go:164]:
```suggestion
			err := utils.CreateDirectory(dir, 0700)
```
Directories should be `0700` - "execute" permissions for directories allows the user to enter the directory so many commands will fail trying to access a directory at `0600`

**Review by Racer159 — CHANGES_REQUESTED** [review]

**Review by Racer159 — APPROVED** [review]
lgtm
