### PR TITLE
Make the corruption error more clear and fix zarf tools cache-clear

### LINKED ISSUE #813: Package Create Fails to Pull Image with Unclear Error
### Environment
Device and OS: System76 Darter Pro, Pop!_OS 22.04 LTS (Ubuntu-based)
App version: v0.21.3
Kubernetes distro being used: (n/a) v5.4.4
Other:

### Steps to reproduce
1. Use this `zarf.yaml`
    ```yaml
    kind: ZarfPackageConfig
    metadata:
      name: image-woes
      description: "Image Woes"
     # Big Bang / Iron Bank are only amd64
      architecture: amd64

    components:
      - name: cdi
        description: "CDI Importer Image"
        required: false
        images:
          - registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-importer:v1.53.0
    ```

2. Build package
    ```
    zarf package create --confirm -l=trace
    ```

### Expected result

Package is created or an image error informs the user which image failed.

### Actual Result

Package does not create, Zarf provides `Error:  error writing image tarball` without identifying the offending image, even when trace logging is enabled.

### Visual Proof (screenshots, videos, text, etc)

```shell
Saving log file to /tmp/zarf-2022-09-29-12-18-03-1106933235.log
  DEBUG   Log level set to trace
└ (/home/runner/work/zarf/zarf/src/internal/message/message.go:102)
  DEBUG   Loading zarf config zarf.yaml
└ (/home/runner/work/zarf/zarf/src/internal/utils/yaml.go:74)
  DEBUG   config.isCompatibleComponent(cdi, false)
└ (/home/runner/work/zarf/zarf/src/config/config.go:273)
  DEBUG   packager.ComposeComponents()
└ (/home/runner/work/zarf/zarf/src/internal/packager/compose.go:15)
  DEBUG   Creating temp path /tmp/zarf-123146811
└ (/home/runner/work/zarf/zarf/src/internal/utils/io.go:20)
  DEBUG   config.GetSeedImage()
└ (/home/runner/work/zarf/zarf/src/config/config.go:143)
  DEBUG   config.IsZarfInitConfig
└ (/home/runner/work/zarf/zarf/src/internal/message/message.go:102)
  DEBUG   config.BuildConfig(/tmp/zarf-123146811/zarf.yaml)
└ (/home/runner/work/zarf/zarf/src/config/config.go:227)

kind: ZarfPackageConfig
metadata:
  name: image-woes
  description: Image Woes
  architecture: amd64
build:
  terminal: siduri76-4
  user: mikaelvanhemert
  architecture: amd64
  timestamp: Thu, 29 Sep 2022 12:18:03 -0600
  version: v0.21.3
components:
- name: cdi
  description: CDI Importer Image
  images:
  - registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-importer:v1.53.0

  ✔  Create Zarf package confirmed

                                                                                       
  📦 CDI COMPONENT                                                                     
                                                                                       

  ✔  Loading metadata for 1 images.                                                                                                                                                                     
  DEBUG   2022/09/29 12:18:06 Layer sha256:d78c3bef8346d985f5592034b59f7a04381e51df4613b4f25f2fdef288576876 found (compressed) in cache                                                                 
└ (/home/runner/work/zarf/zarf/src/internal/message/message.go:102)
  DEBUG   2022/09/29 12:18:06 Layer sha256:089b5df98aeb58f7c9ed8b3663d6dc9c798fbe5b6d807e8a4564c448f4a98a7d found (compressed) in cache                                                                 
└ (/home/runner/work/zarf/zarf/src/internal/message/message.go:102)
  DEBUG   archive/tar: missed writing 73650057 bytes                                                                                                                                                    
└ (/home/runner/work/zarf/zarf/src/internal/message/message.go:130)
     ERROR:  error writing image tarball                                                                                                                                                                
└ (/home/runner/work/zarf/zarf/src/internal/images/pull.go:90)
     Pulling 1 images (36.23 MBs of 106.47 MBs) ██████████                   34% | 1s
```

### Severity/Priority

Low

### Additional Context

The image can be pulled with Docker

```shell
$ docker pull registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-importer:v1.53.0
v1.53.0: Pulling from platform-one/big-bang/apps/sandbox/cdi/cdi-importer
d78c3bef8346: Pull complete 
089b5df98aeb: Pull complete 
Digest: sha256:f905c0f02bb0f939deaf98b47517e828a2d71e2c5e2df7a81db567910bac2fd8
Status: Downloaded newer image for registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-importer:v1.53.0
registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-importer:v1.53.0
```

Other images in the same repo can be successfully pulled by Zarf. Update the `zarf.yaml` with `registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-operator:v1.53.0` and the package creates cleanly.

```shell
$ zarf package create --confirm

Saving log file to /tmp/zarf-2022-09-29-12-26-43-311058188.log

kind: ZarfPackageConfig
metadata:
  name: image-woes
  description: Image Woes
  architecture: amd64
build:
  terminal: siduri76-4
  user: mikaelvanhemert
  architecture: amd64
  timestamp: Thu, 29 Sep 2022 12:26:43 -0600
  version: v0.21.3
components:
- name: cdi
  description: CDI Importer Image
  images:
  - registry.dso.mil/platform-one/big-bang/apps/sandbox/cdi/cdi-operator:v1.53.0

  ✔  Create Zarf package confirmed

                                                                                       
  📦 CDI COMPONENT                                                                     
                                                                                       

  ✔  Loading metadata for 1 images.                                                                                                                                                                     
  ✔  Pulling 1 images (65.37 MBs)                                                                                                                                                                       
  ✔  Creating SBOMs for 1 images.
```

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This adds a more descriptive error and fixes issues with the cache clear command

## Related Issue

Fixes #813

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist before merging

- [X] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Would you mind dropping a screenshot for the pr of the improved error output?

**Comment by Racer159** [comment]
> 

Sure here ya go:
image

File: src/internal/images/pull.go [hunk 1]
```diff
@@ -87,8 +88,11 @@ func PullAll(buildImageList []string, imageTarballPath string) map[name.Tag]v1.I
 		case update.Error != nil && errors.Is(update.Error, io.EOF):
 			progressBar.Success("Pulling %d images (%s)", len(imageMap), utils.ByteFormat(float64(update.Total), 2))
 			return tagToImage
+		case update.Error != nil && strings.HasPrefix(update.Error.Error(), "archive/tar: missed writing "):
+			// Handle potential image cache corruption with a more helpful error. See L#54 in libexec/src/archive/tar/writer.go
+			message.Fatalf(update.Error, "potential image cache corruption: %s of %v bytes", update.Error.Error(), update.Total)
```
Comment (mikevanhemert) [inline src/internal/images/pull.go:93]: Does it make sens to plug the clear cache command here as a possible fix action?

**Review by mikevanhemert — APPROVED** [review]
Looks good! One tiny question but significantly better than before.

File: src/internal/images/pull.go (hunk 1 above)
Comment (jeff-mccoy) [reply src/internal/images/pull.go:93]: Yes I think we should either mention the command or at least a link to a doc for how to fix it as the message is a bit cryptic otherwise.  Keep in mind most of the time this will be on an internet-connected system when we see this error message.  

Down the road when we embed the docusarus site into the web ui we could just link to that even for airgap.

Comment (Racer159) [reply src/internal/images/pull.go]: How about this:
image
Didn't link to docs since that seemed brittle (and the docs page isn't actually there yet)

**Review by mikevanhemert — APPROVED** [review]

**Review by jeff-mccoy — APPROVED** [review]
