### PR TITLE
Fix error handling when building a zarf package with gitops repos that have `@tag` format

### LINKED ISSUE #210: `zarf package deploy` broken when using gitops with repos that use `@tag` notation
When in when using gitops-service, repos with `@tag` notation fail to resolve when running `zarf package deploy`. This fixes it. I'm guessing what is going on is that the error that is being returned doesn't affect the functionality of the checkout, so it should just be ignored instead of acted on, but you guys are closer to this than I am so feel free to poke holes in it.

image

### PR DESCRIPTION
**Pull request by RothAndrew**
Fix #210

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
I'm going to need some more help understanding this issue / reproducing it.  I have a concern with not handling the error, most functions can have different errors, some that matter, some that don't.  I also cannot reproduce the issue with the `gitops-data` example, do you have an example I can you to reproduce?

**Comment by YrrepNoj** [comment]
I think I might have been seeing this on my umbrella example in my PR branch.

**Comment by RothAndrew** [comment]
It’s happening consistently on my branch for doing Istio with a preloaded cert

**Comment by jeff-mccoy** [comment]
Can you reproduce on a clean branch (master or branch off of master) so we have a good baseline for isolation?

**Comment by RothAndrew** [comment]
Yep

**Comment by RothAndrew** [comment]
It's happening with the `gitops-data` example without making any changes to it.

* `cd examples`
* `make clean build-release package-example-gitops-data vm-init`
* (inside VM) `./zarf init`
  * host? `127.0.0.1`
  * Generate CA? `yes`
  * management? `yes`
  * logging? `no`
  * gitops-service? `yes`
* `./zarf package deploy <TheGitOpsServiceTarball>`

image

**Comment by RothAndrew** [comment]
I'd like to merge this asap since all it does is revert a previous change. We can then add an issue for handling this error properly. Does that work for everyone?

**Comment by jeff-mccoy** [comment]
Still concerning since it's not happening to me on master with that example, but we can proceed with the merge for now I guess.  Will look at this more later on.

**Comment by YrrepNoj** [comment]
That works for me as long as we update the revert _slightly_ so that it doesn't just drops the err but logs it as a warning.

**Comment by YrrepNoj** [comment]
@jeff-mccoy that's weird that it's not happening for you on master, it is for me. Did you build the package from the same cli version? This change is when the package gets created, it just becomes obvious that something is weird when you deploy it.

**Comment by jeff-mccoy** [comment]
Yeah I built from master, but let's just proceed because there other other strange things I need to look at more later on here anyway, like the fact the tag is captured in the url replace name.

**Comment by RothAndrew** [comment]
I'm making the change Jon requested. I'll have it pushed up in a few minutes.

**Comment by RothAndrew** [comment]
whelp, now it's not happening. I wonder if the earlier change from ``` to `"` fixed it and I didn't have it pulled down? If so that's gonna make me feel real dumb

**Comment by jeff-mccoy** [comment]
I live in a state perpetually dumbness, it's not so bad really

**Comment by YrrepNoj** [comment]
It's still happening for me.. I double checked to make sure I had the most recent version of master installed and did a full clean.. Fun!

**Comment by RothAndrew** [comment]
It's definitely still happening to me on master if I try to deploy the `gitops-data` example. What's weird is I'm not seeing the warning messages that I'm expecting when I switch over to this branch and try

**Comment by RothAndrew** [comment]
@YrrepNoj do the warnings that I added look okay? I also updated a couple of error messages in another file to help them be distinguished from eachother

**Comment by YrrepNoj** [comment]
Yeah those logs make sense.

I think I realized what the issue was before hand though. The original line 62 should have been `if err == nil`. There is no error happening (which is why you weren't seeing your logs). But because we had the error check backwards we weren't actually doing any of the work.

**Comment by RothAndrew** [comment]
Ah got it. So instead of doing that let's do a standard fatal in a regular error checking block. I'll make that update and get it pushed out shortly.

**Review by YrrepNoj — APPROVED** [review]

**Comment by RothAndrew** [comment]
@YrrepNoj one more review please then I think we'll be ready to merge

File: cli/internal/git/utils.go [hunk 1]
```diff
@@ -195,7 +195,7 @@ func RemoveHeadCopies(gitDirectory string) []*plumbing.Reference {
 	head, err := repo.Head()
 	if err != nil {
 		logContext.Debug(err)
-		logContext.Fatal("Failed to identify references")
+		logContext.Fatal("Failed to identify references when running `repo.Head()`")
```
Comment (YrrepNoj) [inline cli/internal/git/utils.go:198]: Oh I didn't see this, I won't block this but I wouldn't typically put the function called in a log like this, at least not in a fatal log. It might make more sense in a debugging log since it can help a developer figure out whats wrong but telling an end user what function was called isn't useful information to them.

@jeff-mccoy opinions?

Comment (RothAndrew) [reply cli/internal/git/utils.go:198]: I'll reword it a bit, the intent was to make two different blocks have slightly different error messages. They both used to say the same thing.

**Review by YrrepNoj — DISMISSED** [review]

File: cli/internal/git/utils.go (hunk 1 above)
Comment (RothAndrew) [reply cli/internal/git/utils.go]: updated

**Comment by RothAndrew** [comment]
@YrrepNoj one more review pls, sorry :)

**Review by YrrepNoj — APPROVED** [review]
