### PR TITLE
fix: normalize Zarf command handling in Zarf

### LINKED ISSUE #2026: `zarf tools registry ls <img> --full-ref` has strange port in output
### Environment
Device and OS:  HP ZBook Fury 17 G7 Mobile Workstation / Ubuntu 20.04.6 LTS
App version:  Zarf v0.29.2
Kubernetes distro being used:  k3d version v5.6.0 / k3s version v1.27.4-k3s1
Other:

### Steps to reproduce
1.  Run `zarf tools registry ls ` with the `--full-ref` flag multiple times.

### Expected result
I expect the returned images' registry port to reflect the one I passed in.

### Actual Result
I see a rando registry port output with my result.  And the port seems to change every time I call..?

### Visual Proof (screenshots, videos, text, etc)
```bash
$ zarf tools registry ls 127.0.0.1:31999/tekton-releases/github.com/tektoncd/pipeline/cmd/controller --full-ref
127.0.0.1:41117/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1
127.0.0.1:41117/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1-zarf-3557375598

$ zarf tools registry ls 127.0.0.1:31999/tekton-releases/github.com/tektoncd/pipeline/cmd/controller --full-ref
127.0.0.1:42923/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1
127.0.0.1:42923/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1-zarf-3557375598

$ zarf tools registry ls 127.0.0.1:31999/tekton-releases/github.com/tektoncd/pipeline/cmd/controller --full-ref
127.0.0.1:42461/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1
127.0.0.1:42461/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.50.1-zarf-3557375598
````

### Severity/Priority
Low/Low

### Additional Context
It's my first bug report to this project... so if I did a dumb, be sure to let me know.  Many thanks & keep up the good work!

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This Pr normalizes Zarf command execution in Zarf so that the patterns work correctly when used as a library

## Related Issue

Relates to #1814
Fixes #2026

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/utils/io.go [hunk 1]
```diff
@@ -263,11 +264,29 @@ func GetFinalExecutablePath() (string, error) {
...
 
+// GetFinalExecutableCommand returns the final path to the Zarf executable including and library prefixes and overrides.
+func GetFinalExecutableCommand() (string, error) {
+	// In case the binary is symlinked somewhere else, get the final destination
+	zarfCommand, err := GetFinalExecutablePath()
+	if err != nil {
+		return zarfCommand, err
+	}
+
+	zarfCommand = fmt.Sprintf("%s %s", zarfCommand, config.ActionsCommandZarfPrefix)
```
Comment (Noxsios) [inline src/pkg/utils/io.go:280]: this will result in a double space when used within zarf, as `config.ActionsCommandZarfPrefix` will be `""`

Comment (Noxsios) [reply src/pkg/utils/io.go:280]: and `cmd = strings.ReplaceAll(cmd, "./zarf ", zarfCommand+" ")`

Comment (Racer159) [reply src/pkg/utils/io.go:280]: I was hoping you wouldn't notice :sweat_smile: - it doesn't affect functionality, but I'll fix it lol

**Review by Noxsios — APPROVED** [review]
