### PR TITLE
Better Docker Daemon Support + Cleaner Actions Terminal Output

### LINKED ISSUE #1214: Large (10+GB) Docker images cause excess memory usage when pulled from local Docker daemon
### Environment
Device and OS: Fedora 37 in AWS EC2, self hosted GitHub Actions runner (not containerized)
App version: v0.23.5
Kubernetes distro being used: N/A
Other: _Really_ big Docker images (12-20GB) in local Docker daemon

### Steps to reproduce
1. `docker build` a ~20GB container image
2. Optionally, `docker push` (shouldn't matter, it isn't used).
3. `zarf package create` referencing the just-built image in the local Docker daemon. Log output should include `loading image from docker daemon`.
4. Zarf will be OOM killed

(See https://github.com/naps-dev/mockingbird/pull/3 for GitHub Actions pipeline triggering issue.)

### Expected result
Zarf is not OOM killed.

Large images work fine when not pulled from the local registry (when using `--no-local-images` or on older Zarf versions).

### Actual Result
Zarf is OOM killed due to high memory usage.

### Visual Proof (screenshots, videos, text, etc)

Zarf logs from `/tmp` don't say much except confirming that it is pulling from the Docker daemon: `loading image from docker daemon`. I didn't turn on any specific debug flags though.

<details>
  <summary>/tmp/zarf-2023-01-17-22-54-56-3348030351.log</summary>

```
  DEBUG   2023-01-17T22:54:56Z  -  packager.createComponentPaths({
            "name": "mockingbird",
            "description": "Mockingbird Sandbox",
            "required": true,
            "only": {
              "cluster": {}
            },
            "import": {
              "path": ""
            },
            "scripts": {},
            "manifests": [
              {
                "name": "mockingbird-helm",
                "namespace": "mockingbird",
                "files": [
                  "manifests/namespace.yaml",
                  "manifests/gitrepository.yaml",
                  "manifests/helmrelease.yaml"
                ]
              }
            ],
            "images": [
              "123456789123.dkr.ecr.us-east-1.amazonaws.com/mockingbird:dockerize"
            ],
            "repos": [
              "https://github.com/naps-dev/mockingbird.git"
            ]
          })
└ (/home/runner/work/zarf/zarf/src/pkg/packager/create.go:227)
  •  Loading 3 K8s manifests
  DEBUG   2023-01-17T22:54:56Z  -  Active spinner already exists
└ (/home/runner/work/zarf/zarf/src/pkg/message/spinner.go:24)
  DEBUG   2023-01-17T22:54:56Z  -  Unable to load an existing git credentials file: invalid argument
└ (/home/runner/work/zarf/zarf/src/pkg/utils/auth.go:88)
  DEBUG   2023-01-17T22:54:56Z  -  Unable to load an existing netrc file: invalid argument
└ (/home/runner/work/zarf/zarf/src/pkg/utils/auth.go:167)
  DEBUG   2023-01-17T22:54:56Z  -  Repo already cloned, fetching upstream changes...
└ (/home/runner/work/zarf/zarf/src/internal/packager/git/pull.go:69)
  DEBUG   2023-01-17T22:54:56Z  -  git.fetch([]config.RefSpec(nil))
└ (/home/runner/work/zarf/zarf/src/internal/packager/git/pull.go:71)
  DEBUG   2023-01-17T22:54:56Z  -  Attempting to find ref: []config.RefSpec(nil) for https://github.com/naps-dev/mockingbird.git
└ (/home/runner/work/zarf/zarf/src/internal/packager/git/pull.go:71)
  DEBUG   2023-01-17T22:54:56Z  -  Unable to load an existing git credentials file: invalid argument
└ (/home/runner/work/zarf/zarf/src/pkg/utils/auth.go:88)
  DEBUG   2023-01-17T22:54:56Z  -  Unable to load an existing netrc file: invalid argument
└ (/home/runner/work/zarf/zarf/src/pkg/utils/auth.go:167)
  DEBUG   2023-01-17T22:54:56Z  -  Already fetched requested ref
└ (/home/runner/work/zarf/zarf/src/internal/packager/git/fetch.go:76)
  •  Loading 3 K8s manifests
  •  Loading 3 K8s manifests
  DEBUG   2023-01-17T22:54:56Z  -  Active spinner already exists
└ (/home/runner/work/zarf/zarf/src/pkg/message/spinner.go:24)
  DEBUG   2023-01-17T22:54:56Z  -  loading image from docker daemon: 123456789123.dkr.ecr.us-east-1.amazonaws.com/mockingbird:dockerize
└ (/home/runner/work/zarf/zarf/src/internal/packager/images/pull.go:58)
  •  Loading 3 K8s manifests
```

</details>

Journalctl logs including kernel OOM logs. Also a mention of `dockerd` and a possibly relevant error.

<details>
  <summary>journalctl</summary>

```
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: dockerd invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=-500
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: CPU: 1 PID: 872 Comm: dockerd Not tainted 6.0.10-300.fc37.x86_64 #1
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Hardware name: Amazon EC2 m5.large/, BIOS 1.0 10/16/2017
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Call Trace:
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  <TASK>
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  dump_stack_lvl+0x44/0x5c
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  dump_header+0x4a/0x1ff
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  oom_kill_process.cold+0xb/0x10
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  out_of_memory+0x1be/0x4f0
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  __alloc_pages_slowpath.constprop.0+0xccf/0xe20
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  __alloc_pages+0x209/0x230
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  folio_alloc+0x17/0x50
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  __filemap_get_folio+0x149/0x440
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  filemap_fault+0x151/0x990
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  __do_fault+0x36/0x130
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  do_fault+0x1da/0x440
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  __handle_mm_fault+0x645/0xe10
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  ? __rseq_handle_notify_resume+0x96/0x460
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  handle_mm_fault+0xae/0x290
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  do_user_addr_fault+0x1cd/0x690
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  exc_page_fault+0x70/0x170
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  asm_exc_page_fault+0x22/0x30
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: RIP: 0033:0x5564f00c181d
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Code: Unable to access opcode bytes at RIP 0x5564f00c17f3.
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: RSP: 002b:00007f3a1d4abc20 EFLAGS: 00010202
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: RAX: 0000000000000000 RBX: 0000000000002710 RCX: 00005564f00c181d
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00007f3a1d4abc20
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: RBP: 00007f3a1d4abc30 R08: 000000000246963e R09: 0000000000000000
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: R10: 0000000000000000 R11: 0000000000000202 R12: 00007f3a1d4ab660
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: R13: 0000000000000016 R14: 000000c0000029c0 R15: 00007f3a1ccac000
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel:  </TASK>
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Mem-Info:
                                                     free:24840 free_pcp:62 free_cma:0
                                                     kernel_misc_reclaimable:0
                                                     mapped:2 shmem:7 pagetables:6378 bounce:0
                                                     slab_reclaimable:26368 slab_unreclaimable:32615
                                                     unevictable:0 dirty:0 writeback:0
                                                     active_file:53 inactive_file:6099 isolated_file:36
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: active_anon:346420 inactive_anon:436631 isolated_anon:0
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 active_anon:1385680kB inactive_anon:1746524kB active_file:312kB inactive_file:24076kB unevictable:0kB isolated(anon):0kB isolated(file):256kB mapped:8kB dirty:0kB writeback:0kB shmem:28kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 94208kB writeback_tmp:0kB kernel_stack:3312kB pagetables:25512kB all_unreclaimable? yes
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 DMA free:14336kB boost:0kB min:132kB low:164kB high:196kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15360kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: lowmem_reserve[]: 0 2964 7597 7597 7597
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 DMA32 free:44396kB boost:0kB min:26320kB low:32900kB high:39480kB reserved_highatomic:0KB active_anon:595256kB inactive_anon:792880kB active_file:8kB inactive_file:10412kB unevictable:0kB writepending:0kB present:3129256kB managed:3063720kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: lowmem_reserve[]: 0 0 4632 4632 4632
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 Normal free:40628kB boost:0kB min:41128kB low:51408kB high:61688kB reserved_highatomic:0KB active_anon:790424kB inactive_anon:953644kB active_file:168kB inactive_file:13960kB unevictable:0kB writepending:0kB present:4935680kB managed:4752300kB mlocked:0kB bounce:0kB free_pcp:248kB local_pcp:248kB free_cma:0kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: lowmem_reserve[]: 0 0 0 0 0
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 DMA: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 1*2048kB (M) 3*4096kB (M) = 14336kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 DMA32: 329*4kB (UME) 387*8kB (UME) 183*16kB (UME) 406*32kB (UME) 188*64kB (UME) 64*128kB (UME) 13*256kB (ME) 1*512kB (M) 0*1024kB 0*2048kB 0*4096kB = 44396kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 Normal: 281*4kB (UE) 384*8kB (UE) 953*16kB (UME) 210*32kB (UME) 36*64kB (UE) 57*128kB (UME) 15*256kB (UME) 0*512kB 1*1024kB (M) 0*2048kB 0*4096kB = 40628kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 6210 total pagecache pages
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 8 pages in swap cache
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Free swap  = 0kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Total swap = 7830524kB
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 2020232 pages RAM
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 0 pages HighMem/MovableOnly
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 62387 pages reserved
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 0 pages cma reserved
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: 0 pages hwpoisoned
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Tasks state (memory values in pages):
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    571]     0   571    60380       17   372736      330          -250 systemd-journal
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    596]     0   596     8117        5    86016     1072         -1000 systemd-udevd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    662]   999   662     4082       43    65536      208          -900 systemd-oomd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    663]   193   663     5752       15    77824      970             0 systemd-resolve
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    664]     0   664     3964        1    77824      219             0 systemd-userdbd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    665]     0   665     4471       17    57344      175         -1000 auditd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    692]    81   692     2301        0    57344      190          -900 dbus-broker-lau
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    693]    81   693     1360        0    53248      235          -900 dbus-broker
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    697]     0   697     4857       17    77824      888             0 systemd-logind
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    698]     0   698     4041       21    73728      235             0 systemd-machine
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    700]   996   700    21271       14    73728      163             0 chronyd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    724]     0   724    63716       41   126976      648             0 NetworkManager
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    737]     0   737    13699        3    81920      218             0 gssproxy
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    739]     0   739   336912      123   286720     3068          -999 containerd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    865]     0   865   380720       88   462848     6966          -500 dockerd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    867]     0   867     3507       21    61440      284         -1000 sshd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    869]     0   869      718       12    40960       27             0 agetty
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [    871]     0   871     1360        5    49152       41             0 agetty
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225511]     0 225511     4088        1    73728      454             0 sshd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225515]  1000 225515     5262       20    81920      779           100 systemd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225519]  1000 225519    44267        3   110592     2108           100 (sd-pam)
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225526]  1000 225526     4069        0    73728      464             0 sshd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225527]  1000 225527     1816        3    49152      166             0 bash
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225678]   998 225678   615834        0   208896     1453             0 polkitd
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225697]  1000 225697     1750        0    49152       66             0 runsvc.sh
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225699]  1000 225699    79473        0   401408     1546             0 node
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 225706]  1000 225706   923208      693   536576    13625             0 Runner.Listener
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 241956]  1000 241956   926408      932   532480    12723             0 Runner.Worker
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 242171]  1000 242171     1751        0    53248       74           500 bash
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 242173]  1000 242173  3348327   780200 21868544  1907483           500 zarf
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 242211]     0 242211     4051       17    73728      208             0 systemd-userwor
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 242214]     0 242214     4051        8    73728      211             0 systemd-userwor
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: [ 242225]     0 242225     4051       16    69632      208             0 systemd-userwor
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=docker.service,mems_allowed=0,global_oom,task_memcg=/system.slice/actions.runner.naps-dev.naps-dev-runner.service,task=zarf,pid=242173,uid=1000
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal kernel: Out of memory: Killed process 242173 (zarf) total-vm:13393308kB, anon-rss:3120800kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:21356kB oom_score_adj:500
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal chronyd[700]: Forward time jump detected!
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal systemd[1]: actions.runner.naps-dev.naps-dev-runner.service: A process of this unit has been killed by the OOM killer.
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Shutting down runner listener
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Sending SIGINT to runner listener to stop
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Sending SIGKILL to runner listener
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal chronyd[700]: Can't synchronise: no selectable sources
Jan 18 00:36:53 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Exiting...
Jan 18 00:36:55 ip-999-999-999-999.ec2.internal kernel: oom_reaper: reaped process 242173 (zarf), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal dockerd[865]: time="2023-01-18T00:36:56.738782256Z" level=error msg="Can't add file /var/lib/docker/tmp/docker-export-2503784040/334ad8b9f8ae5746dedade7440101515d6b927666899deedea87137d7800098c/layer.tar to tar: io: read/write on closed pipe"
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal dockerd[865]: time="2023-01-18T00:36:56.738958290Z" level=error msg="Can't close tar writer: io: read/write on closed pipe"
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: 2023-01-18 00:36:56Z: Job convert-vm completed with result: Canceled
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Runner listener exited with error code 0
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal runsvc.sh[225699]: Runner listener exit with 0 return code, stop the service, no retry needed.
Jan 18 00:36:56 ip-999-999-999-999.ec2.internal systemd[1]: actions.runner.naps-dev.naps-dev-runner.service: Failed with result 'oom-kill'.
```
</details>

### Additional Context

With Zarf v0.23.5, using the new  feature "Add support for local docker image and image archives on package create" (#1173), I'm seeing OOM kills when it pulls really large images out of the local Docker daemon.

For context: I'm building KubeVirt virtual machine containerDisk images (~18 GB raw, 12GB after docker targz compression) in a GitHub actions pipeline. (Basically scratch Docker images that contain a VM image.) I then package the Docker image plus a Helm chart with KubeVirt manifests with Zarf. This new feature _should_ be great, I can avoid needlessly re-pulling my just-built image. Except I'm getting OOM killed.

I quickly saw Zarf use around 4.5GB memory usage and climb until it was OOM killed. It completes without issue if I pass `--no-local-images`.

### LINKED ISSUE #1267: Console log shows incorrect commands when `prepare` scripts are run
### Environment
Device and OS: EC2 Ubuntu
App version: 0.23.5
Kubernetes distro being used: n/a
Other:

### Steps to reproduce
1. Have 2 components, both with `prepare:` scripts
2. Run `zarf package create`

### Expected result

Correct commands are logged in "Waiting for command" log messages

### Actual Result

image

### Severity/Priority

Low -- The correct commands are run. It's just the logging that is wrong.

### PR DESCRIPTION
**Pull request by jeff-mccoy**
## Description

Updates local image behavior, changing back to crane first with docker as an optional fallback when needed. Large images from docker will still be slow, but should not cause OOM issues and a new warning was added to communicate an alternate approach to speed up local dev with large images. Also cleans up some of the exec package presentation logic.

## Related Issue

Fixes #1214 
Fixes #1267

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
### Added boolean for when to use existing or new `io.write` behavior to avoid this:
Screenshot 2023-02-07 at 2 24 08 AM

### But still seeing some artifacting that may be related to the spinner `io.write` chagnes...
Screenshot 2023-02-07 at 2 46 48 AM

Screenshot 2023-02-07 at 2 24 46 AM

### Also, windows might not like the for loop we're doing here:
Screenshot 2023-02-07 at 2 47 45 AM

**Comment by jeff-mccoy** [comment]
validate FAQ example:

Screenshot 2023-02-07 at 4 03 18 AM

File: src/internal/packager/images/pull.go [hunk 1]
```diff
@@ -55,178 +53,118 @@ func (i *ImgConfig) PullAll() (map[name.Tag]v1.Image, error) {
...
+	// Load image tarballs from the local filesystem.
 	if strings.HasSuffix(src, ".tar") || strings.HasSuffix(src, ".tar.gz") || strings.HasSuffix(src, ".tgz") {
-		message.Debugf("loading image tarball: %s", src)
+		spinner.Updatef("Reading image tarball: %s", src)
 		return crane.Load(src, config.GetCraneOptions(true)...)
 	}
 
-	// Unless disabled, attempt to pull the image from the local daemon
-	if !i.NoLocalImages {
+	// If crane is unable to pull the image, try to load it from the local docker daemon.
```
Comment (YrrepNoj) [inline src/internal/packager/images/pull.go:117]: This comment implies that pulling from remote is the default location but the comment on line 160 seems to imply that pulling from local is the default location.

**Review by YrrepNoj — CHANGES_REQUESTED** [review]

File: docs/9-faq.md [hunk 2]
```diff
@@ -31,6 +30,37 @@ Resources can be excluded at the namespace or resources level by adding the `zar
...
 
+## How can I improve the speed of loading larges images from Docker on `zarf package create`?
+
+Due to some limitations with how Docker provides access to local image layers, `zarf package create` has to rely on `docker save` under the hood that is [very slow overall](https://github.com/defenseunicorns/zarf/issues/1214) and also takes a long time to report progress. We experimented with a lot of ways to improve this, but for now recommend leverage a local docker registry to speed up the process. This can be done by running a local registry and pushing the images to it before running `zarf package create`. This will allow `zarf package create` to pull the images from the local registry instead of Docker. This can also be combined with [component actions](4-user-guide/5-component-actions.md) to make the process automatic. Given an example image of `my-giant-image:###ZARF_PKG_VAR_IMG###` you could do something like this:
```
Comment (Racer159) [inline docs/9-faq.md:35]:
```suggestion
Due to some limitations with how Docker provides access to local image layers, `zarf package create` has to rely on `docker save` under the hood which is [very slow overall](https://github.com/defenseunicorns/zarf/issues/1214) and also takes a long time to report progress. We experimented with many ways to improve this, but for now recommend leveraging a local docker registry to speed up the process. This can be done by running a local registry and pushing the images to it before running `zarf package create`. This will allow `zarf package create` to pull the images from the local registry instead of Docker. This can also be combined with [component actions](4-user-guide/5-component-actions.md) to make the process automatic. Given an example image of `my-giant-image:###ZARF_PKG_VAR_IMG###` you could do something like this:
```

File: examples/component-actions/zarf.yaml [hunk 3]
```diff
@@ -39,6 +39,21 @@ components:
...
+              sleep 1
+              echo "updates!"
+              sleep 3
+              echo "in!"
+              sleep 1
+              echo "realtime!"
+              sleep 1
+            description: multiline & description demo
+          - cmd: sleep 1
+          - cmd: for i in $(seq 1 10); do echo "The current number is $i. I can loop and evaluate expressions too!"; done
```
Comment (Racer159) [inline examples/component-actions/zarf.yaml:56]:
```suggestion
            description: multiline & description demo
```
^ We dont need this and could remove it if it is causing issues.

File: src/internal/packager/git/clone.go [hunk 4]
```diff
@@ -46,7 +46,7 @@ func (g *Git) clone(gitDirectory string, gitURL string, onlyFetchRef bool) (*git
 		return repo, git.ErrRepositoryAlreadyExists
 	} else if err != nil {
 		message.Debugf("Failed to clone repo: %s", err.Error())
-		message.Infof("Falling back to host git for %s", gitURL)
+		g.Spinner.Updatef("Falling back to host git for %s", gitURL)
```
Comment (Racer159) [inline src/internal/packager/git/clone.go:49]: If we switch these back to spinner updates, I would like to the gitURL in the debug message that is right above it since that will go away with the spinner now.

File: src/internal/packager/git/fetch.go [hunk 5]
```diff
@@ -78,7 +78,7 @@ func (g *Git) fetch(gitDirectory string, fetchOptions *git.FetchOptions) error {
 		message.Debug("Already fetched requested ref")
 	} else if err != nil {
 		message.Debugf("Failed to fetch repo: %s", err)
-		message.Infof("Falling back to host git for %s", gitURL)
+		g.Spinner.Updatef("Falling back to host git for %s", gitURL)
```
Comment (Racer159) [inline src/internal/packager/git/fetch.go:81]: Same thing about the gitURL here

File: src/internal/packager/git/pull.go [hunk 6]
```diff
@@ -27,7 +27,7 @@ func (g *Git) DownloadRepoToTemp(gitURL string) string {
 	// packaged anyway, and it saves us from having to fetch the tags
 	// later if we need them
 
-	err = g.pull(gitURL, path, "")
+	_ = g.pull(gitURL, path, "")
```
Comment (Racer159) [inline src/internal/packager/git/pull.go:30]: Can we add a comment as to why we ignore this error

File: src/internal/packager/images/pull.go [hunk 7]
```diff
@@ -55,178 +53,118 @@ func (i *ImgConfig) PullAll() (map[name.Tag]v1.Image, error) {
...
+	if _, err := crane.Manifest(src, config.GetCraneOptions(i.Insecure)...); err != nil {
+		message.Debugf("crane unable to pull image %s: %s", src, err)
+		spinner.Updatef("%s not found, trying with docker instead. This may take some time.", src)
```
Comment (Racer159) [inline src/internal/packager/images/pull.go:120]: Can we make it clearer that we are checking online here?
```suggestion
		spinner.Updatef("%s not found online, trying with docker instead. This may take some time.", src)
```

File: src/internal/packager/images/pull.go [hunk 8]
```diff
@@ -55,178 +53,118 @@ func (i *ImgConfig) PullAll() (map[name.Tag]v1.Image, error) {
...
 
 	// We were unable to pull from the local daemon, so attempt to pull from the wider internet
-	img, err := crane.Pull(src, config.GetCraneOptions(i.Insecure)...)
-	if err != nil {
+	if img, err = crane.Pull(src, config.GetCraneOptions(i.Insecure)...); err != nil {
 		return nil, fmt.Errorf("failed to pull image %s: %w", src, err)
 	}
 
-	message.Debugf("loading image with cache: %s", src)
+	spinner.Updatef("Preparing imagce %s", src)
```
Comment (Racer159) [inline src/internal/packager/images/pull.go:165]:
```suggestion
	spinner.Updatef("Preparing image %s", src)
```

File: src/pkg/packager/actions.go [hunk 9]
```diff
@@ -181,28 +190,42 @@ func actionGetCfg(cfg types.ZarfComponentActionDefaults, a types.ZarfComponentAc
...
+	out, errOut, err := exec.CmdWithContext(ctx, execCfg, shell, shellArgs, cmd)
+	// Dump final complete output.
+	message.Debug(cmd, out, errOut)
+
+	return out, err
+}
+
+func escapeCmdForPrint(cmd string) string {
+	cmdEscaped := strings.ReplaceAll(cmd, "\n", "; ")
+	// Truncate the command if it is longer than 60 characters (to fit well in 80 chars)
```
Comment (Racer159) [inline src/pkg/packager/actions.go:226]: `    Waiting for command "" (timeout: 000s) (000s)` is 49 chars long so would recommend maxing this out at ~30 chars instead for 80 columns (or shortening that printout).

File: src/test/e2e/02_component_actions_test.go [hunk 10]
```diff
@@ -38,6 +38,11 @@ func TestComponentActions(t *testing.T) {
 	// Try creating the package to test the onCreate actions.
 	stdOut, stdErr, err := e2e.execZarfCommand("package", "create", "examples/component-actions", "--confirm")
 	require.NoError(t, err, stdOut, stdErr)
+	require.Contains(t, stdErr, "Completed command \"multiline & description demo\"")
+	require.Contains(t, stdErr, "The current number is 1. I can loop and evaluate expressions too!")
+	require.Contains(t, stdErr, "The current number is 2. I can loop and evaluate expressions too!")
+	require.Contains(t, stdErr, "The current number is 3. I can loop and evaluate expressions too!")
+	require.Contains(t, stdErr, "Completed command \"for i in $(seq 1 10); do echo \"The current number is $i. ...\"")
```
Comment (Racer159) [inline src/test/e2e/02_component_actions_test.go:45]:
```suggestion

```
We could drop the fancy for loop...

**Review by Racer159 — CHANGES_REQUESTED** [review]

File: src/internal/packager/images/pull.go [hunk 11]
```diff
@@ -55,178 +53,118 @@ func (i *ImgConfig) PullAll() (map[name.Tag]v1.Image, error) {
...
+		// This will also take for ever to load large images.
+		if img, err = daemon.Image(reference, daemon.WithUnbufferedOpener()); err != nil {
+			return nil, fmt.Errorf("failed to load image %s from docker daemon: %w", src, err)
 		}
+
+		// If we were able to pull from the local daemon, return the image.
+		return img, err
 	}
 
 	// We were unable to pull from the local daemon, so attempt to pull from the wider internet
```
[the remark this answers is not in the document]
Comment (jeff-mccoy) [reply src/internal/packager/images/pull.go:160]: in this conditional block it is the default, this is a fallback when crane couldnt load the image

File: src/internal/packager/git/pull.go (hunk 6 above)
Comment (jeff-mccoy) [reply src/internal/packager/git/pull.go:30]: I actually dont know why we are.........

File: src/internal/packager/images/pull.go (hunk 7 above)
Comment (jeff-mccoy) [reply src/internal/packager/images/pull.go:120]: yeah but this also could just be some funky auth thing that we are falling back to, so it could still be online. Any suggestion?

File: src/pkg/packager/actions.go (hunk 9 above)
Comment (jeff-mccoy) [reply src/pkg/packager/actions.go:226]: Yeah I actually played with that for a bit last night too, it looked super dumb to truncate scripts that early and adding conditional logic for the different lengths seemed sort of silly. We have lots of text that runs over 80 right now

File: src/internal/packager/git/clone.go (hunk 4 above)
Comment (jeff-mccoy) [reply src/internal/packager/git/clone.go:49]: I suppose that's fair--though the log file will still have it even if not in debug :-)

File: src/internal/packager/images/pull.go (hunk 7 above)
Comment (Racer159) [reply src/internal/packager/images/pull.go:120]: Maybe just `Falling back to docker for %s. This may take some time.` Since we can't accurately state the reason?

File: src/pkg/packager/actions.go (hunk 9 above)
Comment (Racer159) [reply src/pkg/packager/actions.go:226]: Then the comment should say 110 chars not 80 ;)

File: src/internal/packager/git/pull.go (hunk 6 above)
Comment (Racer159) [reply src/internal/packager/git/pull.go:30]: Yeah I think DownloadRepo to temp is used by our helm chart logic only. We fatalf above, could we fatalf here too?

Comment (jeff-mccoy) [reply src/internal/packager/git/pull.go:30]: we've been trying to remove all the fatals from the git package actually

Comment (Racer159) [reply src/internal/packager/git/pull.go:30]: Then we can refactor it to return an error instead potentially.  Or if we want to do that in another PR add a TODO comment.

**Review by YrrepNoj — DISMISSED** [review]

**Comment by Madeline-UX** [comment]
@jeff-mccoy Appreciate the addition of the warning regarding the file size and suggestions for how they can optimize in docs - need to make sure that link never dies lol

**Review by Madeline-UX — APPROVED** [review]

**Review by Racer159 — DISMISSED** [review]
lgtm

**Review by Racer159 — APPROVED** [review]
orange crush
