### PR TITLE
fix: multi-part tarballs being mismatched sizes

### LINKED ISSUE #2313: Unevenly sized multi-part packages
### Environment
Device and OS: System76 darp8
App version: v0.32.3
Kubernetes distro being used: n/a
Other: n/a

### Steps to reproduce
1. Create a package with `--max-package-size` set smaller than the resulting package

### Expected result

Even chunks of a package are created
image

### Actual Result

Varying chunks are created
image

### Severity/Priority

Medium

### Additional Context

This effectively breaks this feature on v0.32.3 - workaround for now is to downgrade to v0.32.2 for those who need this

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This fixes multipart tarballs being different sizes with `--max-package-size`

## Related Issue

Fixes #2313

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

File: src/pkg/utils/io.go [hunk 1]
```diff
@@ -404,10 +404,14 @@ func SplitFile(srcFile string, chunkSizeBytes int) (err error) {
...
+			err = chunkFile.Close()
+			if err != nil {
+				return err
+			}
 
 			// create new file
-			path = fmt.Sprintf("%s.part%03d", srcFile, len(fileNames)+1)
-			chunkFile, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
+			path = fmt.Sprintf("%s.part%03d", srcPath, len(fileNames)+1)
+			chunkFile, err = os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
```
Comment (daniel-palmer-gu) [inline src/pkg/utils/io.go:414]: That's unfortunate. I had fixed this at one point. Seemed to have lost this somehow. Thanks for fixing it!

File: src/test/e2e/05_tarball_test.go [hunk 2]
```diff
@@ -36,6 +37,21 @@ func TestMultiPartPackage(t *testing.T) {
...
+	require.NoError(t, err)
+	require.Equal(t, int64(1000000), part2FileInfo.Size())
+	// Check the package data is correct
+	pkgData := types.ZarfSplitPackageData{}
+	part0File, err := os.ReadFile(parts[0])
+	require.NoError(t, err)
+	err = json.Unmarshal(part0File, &pkgData)
+	require.NoError(t, err)
+	require.Equal(t, pkgData.Count, 6)
+	fmt.Printf("%#v", pkgData)
```
Comment (daniel-palmer-gu) [inline src/test/e2e/05_tarball_test.go:54]: Just so you are aware, the original code would pass this test since the buffer size will dynamically change if it is is below 16MiB. Only when --max-package-size > 17 does the error show up.

Comment (Racer159) [reply src/test/e2e/05_tarball_test.go]: Good point! updated

**Comment by Racer159** [comment]
(putting this in draft since the s3 file needs to be bigger)

File: src/pkg/packager/sources/split.go [hunk 3]
```diff
@@ -85,6 +85,12 @@ func (s *SplitTarballSource) Collect(dir string) (string, error) {
 		if _, err = io.Copy(pkgFile, f); err != nil {
 			return "", fmt.Errorf("unable to copy file %s: %w", file, err)
 		}
+
+		// Close the file when done copying
+		err = f.Close()
+		if err != nil {
+			return "", fmt.Errorf("unable to close file %s: %w", file, err)
+		}
```
Comment (AustinAbro321) [inline src/pkg/packager/sources/split.go:93]:
```suggestion
		if err := f.Close(); err != nil {
			return "", fmt.Errorf("unable to close file %s: %w", file, err)
		}
```
Back to style conversation here https://github.com/defenseunicorns/zarf/issues/2312, do we want to enforce things like this. Something to discuss

File: src/test/e2e/05_tarball_test.go [hunk 4]
```diff
@@ -29,13 +30,28 @@ func TestMultiPartPackage(t *testing.T) {
 	e2e.CleanFiles(deployPath, outputFile)
 
 	// Create the package with a max size of 1MB
```
Comment (lucasrod16) [inline src/test/e2e/05_tarball_test.go:32]: nit: comment wasn't updated to reflect what the code is doing

I'd also be okay with deleting the comment because it's self-explanatory IMO

Other than that, this lgtm

```suggestion
	// Create the package with a max size of 20MB
```

**Review by lucasrod16 — APPROVED** [review]

**Review by lucasrod16 — APPROVED** [review]
lgtm
