### PR TITLE
Defer test cleanup function

### LINKED ISSUE #396: E2E tests don't cleanup properly on failure.
When looking at failed E2E test logs I realized I wasn't seeing any logs for the cluster being torn down after a failed `require...` check. This is because the cleanup function wasn't getting deferred and never being called because the function exited too soon.

### Steps to reproduce
*  Have an e2e test fail while running on a k3s cluster

### Expected result
* e2e cluster gets cleaned up after each test case when `e2e.cleanupAfterTest(...)` is called

### Actual Result
* `require.NoError()` fails the test and stops further progress which leads to the cleanup function never getting called.

### PR DESCRIPTION
**Pull request by YrrepNoj**
## Description

use `defer` to ensure the cleanup function gets run after each test case, even (especially..) if the case failed a require check.

## Related Issue

Fixes #396 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: test/e2e/common.go [hunk 1]
```diff
@@ -273,7 +274,7 @@ func (e2e *ZarfE2ETest) checkIfClusterRunning() bool {
 
 func (e2e *ZarfE2ETest) waitForHealthyCluster() error {
 	attempt := 0
-	for attempt < 10 {
+	for attempt < 15 {
```
Comment (jeff-mccoy) [inline test/e2e/common.go:277]: any details on why this change was needed?  Nbd, just curuious

**Review by jeff-mccoy — DISMISSED** [review]

File: test/e2e/common.go (hunk 1 above)
Comment (YrrepNoj) [reply test/e2e/common.go:277]: I noticed a k3d test failed once because the cluster didn't have enough time to be healthy. It's somewhat a shot in the dark but I figured it wouldn't hurt to give the runners a few extra seconds to spinup the cluster since we don't actually know the underlying specs of the hardware.

**Review by jeff-mccoy — APPROVED** [review]
