### PR TITLE
Fix/zarf agent flux mutation

### LINKED ISSUE #564: The Zarf Agent mutating webhook mutates objects on `CREATE` only, not `UPDATE`
### Environment
Device and OS: EC2 instance running Ubuntu
App version: v0.19.5
Kubernetes distro being used: K3s v1.21.6+k3s1
Other:

### Steps to reproduce
1. Deploy a Flux-based setup that uses GitRepositories, where the `url:` param uses an "upstream" url that isn't "zarf-ified"
2. Update one of the GitRepositories in your config repo and push that new commit to gitea so that flux picks it up

### Expected result

The `url:` param still specifies a "zarf-ified" URL due to a mutation from the zarf agent

### Actual Result

The `url:` param now specifies the upstream "non-zarf-ified" URL

### Visual Proof (screenshots, videos, text, etc)

image

### Severity/Priority

Medium, this is gonna cause things to break in [DI2-ME](https://github.com/defenseunicorns/zarf-package-software-factory), but it won't imminently cause a production-down event

### Additional Context

The mutating webhook for [pods](https://github.com/defenseunicorns/zarf/blob/b1cf764340a8c0210435934f2543369d94c9f4b1/packages/zarf-agent/manifests/webhook.yaml#L36) as well as [GitRepositories](https://github.com/defenseunicorns/zarf/blob/b1cf764340a8c0210435934f2543369d94c9f4b1/packages/zarf-agent/manifests/webhook.yaml#L77) specify `CREATE` as the only operation when the agent will mutate the object. It should specify both `CREATE` and `UPDATE`.

### LINKED ISSUE #610: Unable to Deploy Zarf's Big Bang Core Package
I'm unable to deploy zarf's big bang core package. When I ran the zarf deploy command I can see the big bang helm chart get installed (via the trace logs) but the flux source controller is unable to access the BB gitops repo from gitea. 

This is the error I see in the K8 console. 

_HelmChart 'bigbang/bigbang-bigbang' is not ready_

&& _no artifact available for GitRepository source 'bigbang'_

I can confirm that the gib bang gitops repo is available in gitea 

image

### Environment
Device and OS: Validated on both Azure AKS and K8 Kind Linux Ubuntu 20.04
App version: 0.19.6
Kubernetes distro being used: 1.21.9
Other: 

### Steps to reproduce
```
git clone https://github.com/defenseunicorns/zarf.git
cd zarf/packages/big-bang-core
zarf init --confirm --components git-server
zarf package create --confirm
zarf package deploy "zarf-package-big-bang-core-demo-amd64.tar.zst" -l=trace
```

### Expected result
I would expect that the big bang helm chart would be applied to the cluster and I can see the core namespaces provisioned with the appropriate resources.

### Actual Result
```
kubectl get ns
NAME                 STATUS   AGE
bigbang              Active   13h
default              Active   13h
flux-system          Active   13h
kube-node-lease      Active   13h
kube-public          Active   13h
kube-system          Active   13h
local-path-storage   Active   13h
zarf                 Active   13h
``` 

image

### Severity/Priority
😕 Blocked on deploying services to a big bang cluster via zarf

### LINKED ISSUE #616: Unable to deploy big-bang-core demo
### Environment
Device and OS: ubuntu ec2 
App version: zarf `v0.19.6` 
Kubernetes distro being used: k3d 1.21.7+k3s1
Other:

### Steps to reproduce
1.pulled v0.19.6 over to a ubuntu machine running k3d
2. Cloned the zarf repository
4. Ran a `zarf create package` under zarf/packages/big-bang-core
3. Ran `zarf init` and then `zarf package deploy zarf-package-big-bang-core-demo-amd64.tar.zst`

### Expected result
big bang core demo is deployed
### Actual Result
bigbang gitrepo is stuck due to failing during the mutating webhook call
### Visual Proof (screenshots, videos, text, etc)
zarf-agent logs
```
  DEBUG   http.Serve()(writer, /mutate/flux-gitrepository?timeout=10s)
└ (/home/runner/work/zarf/zarf/src/internal/agent/http/handlers.go:33)

  DEBUG   operations.Execute(*admission.AdmissionRequest) - source.toolkit.fluxcd.io/v1beta2, Kind=GitRepository , bigbang/bigbang: UPDATE
└ (/home/runner/work/zarf/zarf/src/internal/agent/operations/hook.go:30)

  DEBUG   operation UPDATE is not registered
└ (/home/runner/work/zarf/zarf/src/internal/agent/http/handlers.go:65)
 WARNING  Unable to bind the webhook handler
 ```

### PR DESCRIPTION
**Pull request by jeff-mccoy**
## Description
- Proper binding of CREATE and UPDATE for Pods and Gitrepositories
- Add open source flux example for testing
- Add E2E for Flux
- Add retry logic for zarf connect/tunnel establishment
- Fix test stability issues with zarf connect actions and data injection tests
- Move to self-hosted runners

Fixes #564
Fixes #616
Fixes #610 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist before merging
- [x] Tests have been added/updated as necessary (add the `needs-tests` label)

### CODE REVIEW

File: src/test/e2e/22_git_and_flux_test.go [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+	// Deploy the flux example and verify that it works
+	path = fmt.Sprintf("build/zarf-package-flux-test-%s.tar.zst", e2e.arch)
+	stdOut, stdErr, err = e2e.execZarfCommand("package", "deploy", path, "--confirm")
+	require.NoError(t, err, stdOut, stdErr)
+
+	// Temp hack, wait for 30 seconds for flux things
+	time.Sleep(30 * time.Second)
+
+	// Check that flux deployed the podinfo example
+	kubectlOut, _ := exec.Command("kubectl", "wait", "deployment", "-n=podinfo", "podinfo", "--for", "condition=Available=True", "--timeout=60s").Output()
```
Comment (YrrepNoj) [inline src/test/e2e/22_git_and_flux_test.go:70]: I don't know if this 60s timeout is enough time on slower runners 🙃

File: packages/zarf-agent/zarf.yaml [hunk 2]
```diff
@@ -7,9 +7,9 @@ components:
   - name: zarf-agent
     required: true
     images:
-      - "defenseunicorns/zarf-agent:v0.19.5"
+      - "defenseunicorns/zarf-agent:992efd"
```
Comment (YrrepNoj) [inline packages/zarf-agent/zarf.yaml:10]: I know we are going to change how we do agent versioning in the future when we can add values at build/run time. 

How is the versioning going to work in the mean time?

**Comment by YrrepNoj** [comment]
Verifying that this PR fixes the issue we were seeing with updating the helm-releases when deploying the `packages/big-bang-core/zarf.yaml` package.

Screen Shot 2022-07-12 at 11 24 46 AM

**Comment by RothAndrew** [comment]
Is there anything we can do to get this merged today? There's been quite a few issues raised in the last few days where people are running into this bug and don't know why.

**Comment by jeff-mccoy** [comment]
Yeah I'm going to go over all this in a bit (post Dr-pepper). I also have a patch for zarf agent I want to test via sget for existing effected envs.

**Comment by jeff-mccoy** [comment]
If someone wants to take a look at the failing kind test that would be great.

**Comment by YrrepNoj** [comment]
I'm looking at the kind test now, might have to turn tracing on but I'm running the tests locally on KinD at the moment.

File: src/test/e2e/22_git_and_flux_test.go [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+			namespace: "podinfo",
+			name:      "zarf-raw-podinfo-via-flux",
+		},
+		ChartTarget{
+			namespace: "flux",
+			name:      "zarf-raw-flux-crds",
+		},
+		ChartTarget{
+			namespace: "zarf",
+			name:      "zarf-gitea",
```
[the remark this answers is not in the document]
Comment (jeff-mccoy) [reply src/test/e2e/22_git_and_flux_test.go:84]: Yes we are removing the resources as we can to avoid resource issues on the 2-core Github runner.

[the remark this answers is not in the document]
Comment (jeff-mccoy) [reply src/test/e2e/22_git_and_flux_test.go:84]: I also don't think we'll add much more to the git tests unless there is totally new functionality or we say support ArgoCD in the webhook later on.

File: packages/zarf-agent/zarf.yaml (hunk 2 above)
Comment (jeff-mccoy) [reply packages/zarf-agent/zarf.yaml:10]: I'm just changing to the commit hash it was built from so it's more accurate for now.

**Review by Racer159 — DISMISSED** [review]
Me likey.

File: packages/zarf-agent/zarf.yaml (hunk 2 above)
Comment (Racer159) [reply packages/zarf-agent/zarf.yaml:10]: Personally I think this is fine for now (it is more traceable this way).  If we do change agent versioning soon then we can address that without much user impact (would just be an updated version to them).

**Review by Racer159 — APPROVED** [review]
